name: "DevSecOps: Guardián de Secretos"

# El disparador 'workflow_call' es lo que lo hace REUTILIZABLE para n proyectos
on:
  workflow_call:

jobs:
  trufflehog:
    name: Escaneo de Secretos (TruffleHog)
    runs-on: ubuntu-latest
    steps:
      - name: Clonar el código del proyecto
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Escanea todo el historial de Git, no solo el último cambio

      - name: Ejecutar TruffleHog OSS
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          base: ${{ github.event.repository.default_branch }}
          head: HEAD
          extra_args: --debug --only-verified # Solo alerta si la llave es funcional (reduce falsos positivos)