name: "Security - Secrets Audit"

on:
  workflow_call:

jobs:
  secrets-audit:
    name: "1. Guardian de Secretos"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Codigo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Prepare Results Directory
        run: |
          mkdir -p security-results
          echo "Workspace: $(pwd)"

      - name: Scan Secrets (TruffleHog)
        run: |
          docker run --rm -v "$PWD:/pwd" -w /pwd trufflesecurity/trufflehog:latest \
            github --repo="${{ github.event.repository.html_url }}" --json \
            > security-results/trufflehog-results.json

          # Si el archivo tiene contenido → fallo
          if [ -s security-results/trufflehog-results.json ]; then
            echo "❌ Secretos detectados"
            exit 1
          fi

      - name: Debug TruffleHog Output
        if: always()
        run: |
          pwd
          ls -la
          ls -la security-results || true

      - name: Save Secrets Result
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: security-trufflehog
          path: security-results/trufflehog-results.json
          if-no-files-found: warn
          retention-days: 1