name: "Security - SBOM"

on:
  workflow_call:
    inputs:
      java-version:
        type: string
        default: '21'

jobs:
  sbom-generation:
    name: "3.5 Inventario SBOM"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Codigo
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: ${{ inputs.java-version }}
          distribution: 'temurin'

      - name: Generar SBOM
        run: mvn org.cyclonedx:cyclonedx-maven-plugin:makeAggregateBom -Dcyclonedx.skipAttach=true

      - name: Upload SBOM Artifact
        uses: actions/upload-artifact@v4
        with:
          name: project-sbom
          path: target/bom.json
