name: "Security - SBOM"

on:
  workflow_call:
    inputs:
      java-version:
        type: string
        default: '21'

jobs:
  sbom-generation:
    name: "5. SBOM Inventory"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Codigo
        uses: actions/checkout@v4

      - name: Preparar directorio
        run: mkdir -p security-results

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: ${{ inputs.java-version }}
          distribution: 'temurin'
          cache: 'maven'

      - name: Generar SBOM (CycloneDX)
        run: |
          mvn -B org.cyclonedx:cyclonedx-maven-plugin:makeAggregateBom \
            -Dcyclonedx.skipAttach=true

          cp target/bom.json security-results/sbom.json

      - name: Validar existencia SBOM
        run: |
          if [ ! -f security-results/sbom.json ]; then
            echo "❌ No se generó SBOM"
            exit 1
          fi

      - name: Validar estructura JSON
        run: |
          jq empty security-results/sbom.json

      - name: Métricas SBOM
        run: |
          echo "📊 SBOM Metrics"

          TOTAL_COMPONENTS=$(jq '.components | length' security-results/sbom.json)

          echo "Total Components: $TOTAL_COMPONENTS"

      - name: Debug SBOM (estructura)
        run: |
          echo "===== KEYS ====="
          jq 'keys' security-results/sbom.json

          echo "===== METADATA ====="
          jq '.metadata' security-results/sbom.json

      - name: Upload SBOM Artifact
        uses: actions/upload-artifact@v4
        with:
          name: security-sbom
          path: security-results/sbom.json
          retention-days: 5