name: "Security - SCA Snyk"

on:
  workflow_call:
    inputs:
      java-version:
        type: string
        default: '21'
    secrets:
      SNYK_TOKEN:
        required: true

jobs:
  dependency-scan:
    name: "3. SCA (Snyk)"
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout Codigo
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: ${{ inputs.java-version }}
          distribution: 'temurin'

      - name: Run Snyk
        run: |
          npm install -g snyk
          snyk auth ${{ secrets.SNYK_TOKEN }}
          snyk test --file=pom.xml --json > snyk-results.json || true

      - name: Upload Snyk Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: snyk-report
          path: snyk-results.json
