name: "Security - Secrets Audit"

on:
  workflow_call:

jobs:
  secrets-audit:
    name: "1. Guardian de Secretos"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Codigo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Scan Secrets (TruffleHog)
        run: |
          docker run --rm -v "$PWD:/pwd" trufflesecurity/trufflehog:latest github --repo="${{ github.event.repository.html_url }}" --json > trufflehog-results.json
        continue-on-error: true

      - name: Save Secrets Result
        uses: actions/upload-artifact@v4
        with:
          name: secrets-report
          path: trufflehog-results.json
          retention-days: 1