name: "Security - Secrets Audit"

on:
  workflow_call:

jobs:
  secrets-audit:
    name: "1. Guardian de Secretos"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Codigo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          base: ${{ github.event.repository.default_branch }}
          head: HEAD
          extra_args: --only-verified
