name: "Motor: Escaneo de Librerías (SCA)"

on:
  workflow_call:
    secrets:
      SNYK_TOKEN:
        required: true

jobs:
  snyk:
    name: Snyk Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar Java (Necesario para Snyk en Java)
        uses: actions/setup-java@v4
        with:
          java-version: '21' 
          distribution: 'temurin'

      - name: Ejecutar Snyk para buscar vulnerabilidades
        uses: snyk/actions/maven@master # O 'gradle' si usan Gradle
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=high # Solo falla si hay algo GRAVE